import Navbar from "./Navbar.js"
// import Footer from "../Footer/Footer.js"
import Head from "next/head"

const Layout = ({ children }) =>{
  return (
    <>
          <Head>
        <title>MARC MCKIRAHAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon"/>
      </Head>
      <Navbar />
      <main>{children}</main>
      {/* <Footer /> */}
    </>
  );
}

export default Layout